### ISSUE TITLE
about our torchmd

### ISSUE THREAD

**Issue by wwang2** [torchmd/torchmd#13]
Hi TorchMD developers 

 I recently came across this repo and really liked it for its great software engineering. I will potentially use this for my own work. Hope you don't mind getting in touch.

I just want to share our project here https://github.com/wwang2/torchmd which has a very similar name.  I just want to raise an issue here because I can imagine it might confuse some people in the community due to naming collision. I can also try to be creative to come up with a new name for my repo, but I am open to other proposals.

Our project focuses more on the differentiability of observables from molecular simulations for control and force field fitting tasks. We use the adjoint sensitivity implementation for the verlet integration which has a huge memory benefit for backpropagating over long trajectories for large systems compared with direct backpropgation. We are also experimenting with other techniques like checkpointing and forward-mode AD. 

I would also be happy to write some interfacing code to bridge TorchMD with torchmd so that the community might be able to use the nice features of both repositories.

Looking forward to more discussions.

Wujie

**Comment by franknoe** [comment]
Hi Wujie, thanks for reaching out. This is @giadefa 's call, but I think there's definitely overlap of interests and functionalities. Since both projects are fairly young we can also think about merging functionalities.

**Comment by giadefa** [comment]
HI Wujie,
we were aware of your repo, but I think to remember that there was no code
in it. I see that now you have code, so it would be great to collaborate.
I'll write to you and Rafael.

Best,
Gianni.
