### ISSUE TITLE
Is it possible to perform NPT simulation with torchmd?

### ISSUE THREAD

**Issue by siddharth-ncl-work** [torchmd/torchmd#17]
Hi,
I have gone through the tutorials but couldn't find NPT simulation example (let me know if I missed it). Is it possible to perform NPT simulation with torchmd? If yes, can you please explain how to do so. Thanks

**Comment by giadefa** [comment]
no

**Comment by siddharth-ncl-work** [comment]
Is there any plan to include NPT simulation functionality in the future release?

**Comment by giadefa** [comment]
No. I really don't see any point in that. Can you explain why you think
that you need that?

**Comment by siddharth-ncl-work** [comment]
For one the projects I need to calculate boiling point of the systems containing benzene and methanol. I was asked to perform NPT simulation for that. Unfortunately, the classical force fields don't provide correct answer in all scenarios. One of the solution is to identify the correct values of force field parameters (i.e., charge and vdw epsilon) but this is quite difficult. So, we are thinking of using ML force fields as they don't require parametrization. The issue is even if we train ML models and obtain ML force fields, we can't use them as popular MD engines (eg. GROMAC, GAMESS, CHARMS etc) don't support ML force fields (correct me if I am wrong). Therefore, we are looking for some way to use trained ML force fields for NPT simulation. Hope I am clear. Let me know if you need more information.
I would also appreciate if you have another solutions to this problem.

Thank you

**Comment by raimis** [comment]
@siddharth-ncl-work OpenMM has a plugin for the ML force fields (https://github.com/openmm/openmm-torch) and compatible barostats.

**Comment by siddharth-ncl-work** [comment]
@raimis I will check it out. Thank you for the suggestion.

**Comment by siddharth-ncl-work** [comment]
I am closing this issue. If I need further help on this, I will re-open it. 

Thank you
