### ISSUE TITLE
where is datasheet?  I hope to provide some data sets

### ISSUE THREAD

**Issue by chensusu11** [torchmd/torchmd#22]
![image](https://user-images.githubusercontent.com/44188056/148184125-2c81c9b3-29fd-4ff3-9e66-a69bf77a2d78.png)

Thankyou！I want to try this example！

**Comment by stefdoerr** [comment]
@MaciejMajew do we have the tutorial data somewhere to share?

**Comment by stefdoerr** [comment]
Hi @chensusu11 you can find the example data here: https://github.com/torchmd/torchmd/tree/master/test-data/prod_alanine_dipeptide_amber
