### ISSUE TITLE
Running example fails on computation of forces

### ISSUE THREAD

**Issue by GregorySchwing** [torchmd/torchmd#30]
I am running the example script with the following package versions
moleculekit 1.5.6
torch 1.13.0a0+08820cb

Cuda is available, and there is one device available.
```py
from torchmd.forces import Forces
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())
forces = Forces(parameters, cutoff=9, rfa=True, switch_dist=7.5)
# Evaluate current energy and forces. Forces are modified in-place
Epot = forces.compute(system.pos, system.box, system.forces, returnDetails=True)

print(Epot)#print(system.forces)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [20], in <cell line: 7>()
      5 forces = Forces(parameters, cutoff=9, rfa=True, switch_dist=7.5)
      6 # Evaluate current energy and forces. Forces are modified in-place
----> 7 Epot = forces.compute(system.pos, system.box, system.forces, returnDetails=True)

File /opt/conda/lib/python3.8/site-packages/torchmd/forces.py:278, in Forces.compute(self, pos, box, forces, returnDetails, explicit_forces)
    276     pot[i][v] += E.sum()
    277 elif v == "lj":
--> 278     E, force_coeff = evaluate_LJ(
    279         nb_dist,
    280         ava_idx,
    281         self.par.mapped_atom_types,
    282         self.par.A,
    283         self.par.B,
    284         self.switch_dist,
    285         self.cutoff,
    286         explicit_forces,
    287     )
    288     pot[i][v] += E.sum()
    289 elif v == "repulsion":

File /opt/conda/lib/python3.8/site-packages/torchmd/forces.py:374, in evaluate_LJ(dist, pair_indeces, atom_types, A, B, switch_dist, cutoff, explicit_forces)
    371 def evaluate_LJ(
    372     dist, pair_indeces, atom_types, A, B, switch_dist, cutoff, explicit_forces=True
    373 ):
--> 374     atomtype_indices = atom_types[pair_indeces]
    375     aa = A[atomtype_indices[:, 0], atomtype_indices[:, 1]]
    376     bb = B[atomtype_indices[:, 0], atomtype_indices[:, 1]]

RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Comment by stefdoerr** [comment]
Hi, can you pull the master branch and try again? I made a small fix which might solve this https://github.com/torchmd/torchmd/commit/851eb99eb4080a4b1943fae1d42f54eee1e137f9

**Comment by GregorySchwing** [comment]
It's still failing on that line with a different error.
from torchmd.forces import Forces

print(torch.cuda.is_available())

print(torch.cuda.device_count())

print(torch.cuda.current_device())

forces = Forces(parameters, cutoff=9, rfa=True, switch_dist=7.5)

# Evaluate current energy and forces. Forces are modified in-place

Epot = forces.compute(system.pos, system.box, system.forces, returnDetails=True)

​

print(Epot)#print(system.forces)

True
1
0

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [10], in <cell line: 5>()
      3 print(torch.cuda.device_count())
      4 print(torch.cuda.current_device())
----> 5 forces = Forces(parameters, cutoff=9, rfa=True, switch_dist=7.5)
      6 # Evaluate current energy and forces. Forces are modified in-place
      7 Epot = forces.compute(system.pos, system.box, system.forces, returnDetails=True)

File /opt/conda/lib/python3.8/site-packages/torchmd/forces.py:40, in Forces.__init__(self, parameters, terms, external, cutoff, rfa, solventDielectric, switch_dist, exclusions)
     38 self.par = parameters
     39 if terms is None:
---> 40     raise RuntimeError(
     41         'Set force terms or leave empty brackets [].\nAvailable options: "bonds", "angles", "dihedrals", "impropers", "1-4", "electrostatics", "lj", "repulsion", "repulsioncg".'
     42     )
     44 self.energies = [ene.lower() for ene in terms]
     45 for et in self.energies:

RuntimeError: Set force terms or leave empty brackets [].
Available options: "bonds", "angles", "dihedrals", "impropers", "1-4", "electrostatics", "lj", "repulsion", "repulsioncg".

**Comment by stefdoerr** [comment]
forces = Forces(parameters, cutoff=9, rfa=True, switch_dist=7.5, terms=["bonds", "angles", "dihedrals", "impropers", "1-4", "electrostatics", "lj"])

Try with this
