### ISSUE TITLE
Protein in explicit water solvent box simulation with torchMD

### ISSUE THREAD

**Issue by Byun-jinyoung** [torchmd/torchmd#48]
Is is possible to run MD simulation a large protein (AA>300) in explicit water solvent with torchMD?

Thank you!

**Comment by giadefa** [comment]
in theory yes, in practice it is too slow for that.
You should use ACEMD for fast calculations.
Any reason to use TorchMD?

**Comment by Byun-jinyoung** [comment]
I want to run MD simulation by using TorchMD. and later I'd like to add custom NN potential during MD simulation

**Comment by giadefa** [comment]
you can add an external potential using ACEMD as well. We can help in you
find issues to include torchmd-net into it.
The only reason to use TorchMD if you need to play with the MM part of it.

**Comment by Byun-jinyoung** [comment]
Is it better to upload this issue in torchMD-net GitHub repository?
I'd like to simulation protein in explicit solvent with MD + deep learning approach (e.g. roughly such as OpenMM + openmm-pytorch although I've never used openmm-pytorch...)

**Comment by giadefa** [comment]
It's not really an issue yet. Just try with OpenMM or ACEMD and then post
depending of the problems

**Comment by Byun-jinyoung** [comment]
Okay!
