### ISSUE TITLE
Running MD simulations with NNPs

### ISSUE THREAD

**Issue by saratk1** [torchmd/torchmd#56]
Dear developers,
I would like to run MD simulations with TrochMD-NET, but I can't find an example for that neither in TorchMD-NET nor in TorchMD. In the TorchMD-NET documentation it says, that it is integrated in TorchMD. I have seen your TorchMD tutorial, but I was wondering if you could provide me with a code snippet on how to set up and run such a simulation with e.g. a pre-trained TrochMD-NET `model` (I am particularly interested in how to deal with the `Forces` class). In case I have missed some already existing examples, could you point me that source?
Thank you very much in advance!

**Comment by AntonioMirarchi** [comment]
Hi, you can run md simulation in torchmd using the [torchmd-net external module](https://github.com/torchmd/torchmd-net/blob/main/torchmdnet/calculators.py).  So in your torchmd input.yaml, you should specify:

```
external:
  embeddings: []
  file: "your/file/.ckpt"
  module: torchmdnet.calculators
```

Be careful because TorchMD uses chemical units such as kcal/mol for energies, K for temperatures and Å for distances.  If it's not your case, you can use the output_transform argument to transform it.

**Comment by saratk1** [comment]
Hi,
Thank you for your answer. I tried running the [run.py](https://github.com/torchmd/torchmd/blob/master/torchmd/run.py) script with the external module specified in the `input.yaml` file, but I got the following error:
```
2023-10-09 15:57:40,814 - numexpr.utils - INFO - Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-10-09 15:57:40,814 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
/home/stkaczyk/mambaforge/envs/torchmd-net/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.0' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
Force terms:  ['LJ']
Traceback (most recent call last):
  File "/home/stkaczyk/Documents/work/tautomer_testing/torchmd-net/notebooks/run.py", line 294, in <module>
    mol, system, forces = setup(args)
  File "/home/stkaczyk/Documents/work/tautomer_testing/torchmd-net/notebooks/run.py", line 182, in setup
    parameters = Parameters(
  File "/home/stkaczyk/mambaforge/envs/torchmd-net/lib/python3.10/site-packages/torchmd/parameters.py", line 35, in __init__
    self.build_parameters(ff, mol, terms)
  File "/home/stkaczyk/mambaforge/envs/torchmd-net/lib/python3.10/site-packages/torchmd/parameters.py", line 119, in build_parameters
    self.masses = self.make_masses(ff, mol.atomtype) 
  File "/home/stkaczyk/mambaforge/envs/torchmd-net/lib/python3.10/site-packages/torchmd/parameters.py", line 163, in make_masses
    masses = torch.tensor([ff.get_mass(at) for at in atomtypes])
  File "/home/stkaczyk/mambaforge/envs/torchmd-net/lib/python3.10/site-packages/torchmd/parameters.py", line 163, in <listcomp>
    masses = torch.tensor([ff.get_mass(at) for at in atomtypes])
  File "/home/stkaczyk/mambaforge/envs/torchmd-net/lib/python3.10/site-packages/torchmd/forcefields/ff_yaml.py", line 60, in get_mass
    return self.prm["masses"][at]
KeyError: ''
```
I tried to run it without the torchmd-net `External` calculator and I got the same error.
As input I used a pdb  (`--topology`). [In this case](https://github.com/torchmd/torchmd/blob/0f9dc7b09ae2b6078c23e75a675daac900e4a04c/torchmd/parameters.py#L119) the `atomtypes` are not recognized in the `moleculekit.molecule`.
Do I specify the input topology wrongly? Also, I was wondering, is it possible to use the [Forces class](https://github.com/torchmd/torchmd/blob/0f9dc7b09ae2b6078c23e75a675daac900e4a04c/torchmd/run.py#L216) without specifying any classical parameters?

**Comment by RaulPPelaez** [comment]
Please share your input.yaml so we can debug.
@AntonioMirarchi it looks like the atomtypes in the Molecule object are empty. Can you think of a reason why?

**Comment by stefdoerr** [comment]
I assume they are probably not loading the Molecule from a prmtop file. PDB files for example don't contain atomtypes

**Comment by stefdoerr** [comment]
We could in theory get the masses from elements if no atom types exist. Might make sense when people are not using traditional FF terms and just external calculators to then not need to build the system with AMBER first

**Comment by AntonioMirarchi** [comment]
If you are using `forcefield: null` and the PDB file as input, which lacks information on atom types, then [make_masses()](https://github.com/torchmd/torchmd/blob/0f9dc7b09ae2b6078c23e75a675daac900e4a04c/torchmd/parameters.py#L162-L165) will return a tensor with zero elements (masses) because moleculekit create an array of empty string for the atomtypes: 
`atomtypes : (array['', '', '', ], dtype=object)` and then `masses: tensor([0., 0., 0.,])`. So maybe the problem is not just that. 

To execute without specifying any classical parameters, you can set `forceterms: []` in the YAML.

**Comment by saratk1** [comment]
Just to clarify, does this mean that currently running a MD simulation does not work with pdb as input?

**Comment by AntonioMirarchi** [comment]
It works, just share your config yaml please

**Comment by saratk1** [comment]
Sure, thanks!

```yaml
coordinates: null
cutoff: null
device: cpu
exclusions: !!python/tuple
- bonds
- angles
- 1-4
extended_system: null
external:
  embeddings: []
  file: epoch=359-val_loss=0.0004-test_loss=0.0120.ckpt
  module: torchmdnet.calculators
forcefield: null
forceterms: []
langevin_gamma: 0.1
langevin_temperature: 0
log_dir: ./
minimize: null
npz_file: null
output: output
output_period: 10
precision: single
replicas: 1
rfa: false
save_period: 0
seed: 1
steps: 10000
structure: null
switch_dist: null
temperature: 300
timestep: 1
topology: test.pdb
```

**Comment by AntonioMirarchi** [comment]
Probably it's need to compute the masses from the elements, as suggested by @stefdoerr, if the moleculekit object doesn't have atomtype for any reason.  You can find [here ](https://github.com/AntonioMirarchi/torchmd/tree/make_masses_from_elements) a version of that code that works for me starting from only PDB, in the meanwhile that a final version will merged in the main repo.  

Anyway `torchmdnet.calculators` needs [embedding](https://github.com/torchmd/torchmd-net/blob/f837503b9daedaf5c1870d0198ae6c0ae69a67a2/torchmdnet/calculators.py#L52), and if you are starting from moleculekit object you have to specify it in the input.yaml.

**Comment by saratk1** [comment]
Thank you for the updates! The simulation is running, but just for reference: I changed `mol.z`  in [converter_xyz_output()](https://github.com/torchmd/torchmd/blob/1bad86ec08cec101320d66b24529a032ace4d016/torchmd/run.py#L289) to the atomic numbers, as also suggested [here](https://github.com/torchmd/torchmd/pull/52#issuecomment-1748263207).
