### ISSUE TITLE
Some questions about the units of code 

### ISSUE THREAD

**Issue by YaoHuUstc** [torchmd/torchmd#65]
Hi! I have some questions about the units in the integrator.py
```
TIMEFACTOR = 48.88821

def _first_VV(pos, vel, force, mass, dt):
    accel = force / mass
    pos += vel * dt + 0.5 * accel * dt * dt
    vel += 0.5 * dt * accel


def _second_VV(vel, force, mass, dt):
    accel = force / mass
    vel += 0.5 * dt * accel

dt = timestep / TIMEFACTOR
```
the units of distance time mass and energy are angstrom fs g/mol and kcal/mol,
So when I check the units of the code, I feel confused. First of all, I guess the TIMEFACTOR is try to transfer kcal to kj. But I don't know how it's work, Why does time need to be divided by such a number.
Secondly, in function _first_VV
```
0.5 * accel * dt * dt
```
for example, the accel unit is kcal/(g*Å) dt is 1fs/48.88821, the output unit will be
```
4.184kj/(g*Å) * fs^2 * (1/48.88821)^2 = 4.184 * 10^6 g*m*m/(s*s*g*Å) * fs^2 * (1/48.88821)^2 = 1750 * (m^2)/Å * (fs/s)^2
```
i'm not sure that if dt = timestep * TIMEFACTOR, in this way, the result units will equal to Å

I don't know maybe I get wrong in some place.

Thank you very much. If you could answer my question as soon as possible

**Comment by giadefa** [comment]
This is from the README>

TorchMD uses chemical units consistent with classical MD codes such as ACEMD, namely kcal/mol for energies, K for temperatures, g/mol for masses, and Å for distances.

Time is a derived unit that corresponds to 48.88821 fs. 

The interpretation that you make above is not correct.

**Comment by YaoHuUstc** [comment]
Thank you very much for your answer, but could you tell me why we need to use 48.88821 fs as the derived unit for time
and why
```
dt = timestep / TIMEFACTOR
```
Because I think this should be 
```
dt = timestep * TIMEFACTOR
```
I would greatly appreciate it if you could resolve my confusion

**Comment by giadefa** [comment]
1fs in internal time units is 1/TIMEFACTOR
